library(lattice)
data(quakes)
mini=min(quakes$depth)  
maxi=max(quakes$depth)
int=ceiling((maxi-mini)/9)
inf=seq(mini,maxi,int)
quakes$depth.cat=factor(floor(((quakes$depth-mini)/int)),labels=paste(inf,inf+int,sep="-"))
xyplot(lat~ long | depth.cat, data=quakes)
str(quakes$depth.cat)
